name: dart_game_engine
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '<4.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  meta: ^1.8.0
  equatable: ^2.0.5
  forge2d: ^0.13.0
  dart_amqp: ^0.2.4
dev_dependencies:
  http: ^1.0.0
  lints: ^3.0.0
  test: ^1.15.0
