scrape_configs:
  - job_name: 'consul_registered_services'
    scrape_interval: 10s
    metrics_path: '/prometheus'
    consul_sd_configs:
      - server: 'consul:8500'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job

      # Hide Consul from the targets list
      - source_labels: [ __meta_consul_service ]
        regex: '(^consul)'
        target_label: job
        action: drop



#graphana query: sum by (job) (rate(geofencing_wonderSeeker_fence_intersection_counter_total[$__rate_interval]))